Don't fork in 2.13.0-M5
There is a bug in scaltest that makes the output borderline unreadable
for forked tests and causes problems with the log buffering on travis.

The logs are littered with: Reporter completed abruptly with an exception after receiving event: ScopeOpened(Ordinal(0, 342),PathFinde
rCombinator,NameInfo(PathFinderCombinatorSpec,sbt.io.PathFinderCombinatorSpec,Some(sbt.io.PathFinderCombin
atorSpec),None),Some(IndentedText(PathFinderCombinator,PathFinderCombinator,0)),Some(LineInFile(9,PathFind
erCombinatorSpec.scala,Some(Please set the environment variable SCALACTIC_FILL_FILE_PATHNAMES to yes at co
mpile time to enable this feature.))),None,pool-1-thread-7-ScalaTest-running-PathFinderCombinatorSpec,1551
054035193).
java.net.SocketException: Broken pipe (Write failed)
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
        at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877)
        at java.io.ObjectOutputStream$BlockDataOutputStream.writeByte(ObjectOutputStream.java:1915)
        at java.io.ObjectOutputStream.writeFatalException(ObjectOutputStream.java:1576)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:351)
        at org.scalatest.tools.SocketReporter.apply(SocketReporter.scala:31)
        at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10(DispatchReporter.scala:249)
        at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10$adapted(DispatchReporter.scala:248)
        at scala.collection.immutable.List.foreach(List.scala:302)
        at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:248)
        at java.lang.Thread.run(Thread.java:748)